// Generated by rust-shell-script
mod cmd_lib;
use crate::cmd_lib::{CmdResult, FunResult};

fn error_command() -> CmdResult {
    run_cmd!("do_something_failed")
}

fn bad_greeting(name: &str) -> FunResult {
    info!("Running error_command ...");
    error_command()?;
    output!("hello, {}!", name)
}

fn good_greeting(name: &str) -> FunResult {
    info!("Running good_command ...");
    output!("hello, {}!", name)
}

fn main() -> CmdResult {
    let bad_ans = bad_greeting("rust-shell-script")?;;
    info!("{}", bad_ans);
    let good_ans = good_greeting("rust-shell-script")?;;
    info!("{}", good_ans);
    return Ok(())
}

